### ISSUE TITLE
如何划分base

### ISSUE THREAD

**Issue by jijinlong** [Lang4/server#1]
先划分5个模块
1.network
 2.thread 
3.database
 4.time
 5.xml

**Comment by weizhiwu** [comment]
先弄下vim的设置， vim插件， 文件头， 函数的自动注释规范

开发环境64位linux系统等的建议选择， gcc, g++, gdb等的版本

工程的大概目录结构和框架

makefile的编写

base名字换成其他的

# 

vim 的设置文件都可以先提交到工程下,base 换名成engine?

**Comment by jijinlong** [comment]
看看模块是不是可以独立存在 就如 network 可以方便的被别人使用不需要包含zType.h zThread.h 等文件 network可以独立存在 这样每个模块都可独立存在

**Comment by weizhiwu** [comment]
先把整个工程相关的结构都定好，再开始修改 base基础代码

zType.h  zString.h  zNoncopy.h  global.h zMutext.h  zThread.h zProperty.h 等base的基础 先修改

需要独立存在的库， 就直接用int32, int64,  不用typedef的DWORD， QWORD  估计很多部分都可以独立存在， 写成相互依赖也可以， 反正是整个基础库

**Comment by weizhiwu** [comment]
等前面的部分弄好， 就可以各自选不同的模块写， 网络和数据库封装估计得认真讨论下， 怎么改

**Comment by jijinlong** [comment]
是的 网络库可以做成多个方案 [征途的 boost ACE的 lang/net 的] 我们提供一个接口出来

**Comment by peakflys** [comment]
恩，小武哥说的对，既然是一个集体开发项目，首先开发环境和工具的版本和基本规范先定一下。

**Comment by peakflys** [comment]
编码规范的话，估计不是什么大问题，直接使用征途的那一套也可以，主要是开发环境和工具的版本，因为定位是跨平台，所以编码的时候也要注意一下，尽量不使用特定平台的函数或文件

**Comment by jijinlong** [comment]
是的 考虑到linux 环境不是必备环境 我们将要做window/linux 的同时开发 linux 和 windows 提供一致的上层接口

**Comment by peakflys** [comment]
对了  咱们的定位是做一个服务器引擎吧？

# 

是的，提供相应的demo

**Comment by wuchangxu** [comment]
要想跨平台，尽量用C++11里的东西吧.

# 

vs gcc 都用新版的了

**Comment by dreamingP** [comment]
先打个招呼  呵呵

# 

不能放水啊 下一条无关的 将删

**Comment by dreamingP** [comment]
我感觉是不是可以base下面的各个部分继续细化为各种功能库，然后针对各个功能库进行讨论关于各个细节

# 

可以的 可以先从tcp相关的搞独立起来

**Comment by dreamingP** [comment]
我感觉是不是可以base下面的各个部分继续细化为各种功能库，然后针对各个功能库进行讨论关于各个细节，至于开发工具选择兼容性好的。

**Comment by dreamingP** [comment]
base 下面另外还要加个 日志系统和统计系统

# 

这个就需要dreamingP 来弄了
