### ISSUE TITLE
重构Base库方案

### ISSUE THREAD

**Issue by jijinlong** [Lang4/server#3]
# 主要是网络接口 待定版

<pre>
class ReadFunction {
public:
    void operator()(void *content,unsigned int len)
    {
                        connector->write("hello,world",10); // 发送消息
    }
};
int main()
{
    IConnector *connector = makeConnector(makeAddr("ip",port)); // 创建连接者
    IReactor *reactor = makeReactor(); // 创建反应器 相当于Epoll
    reactor->add(connector); // 加入事件管理
    ReadFunction readCallback; // 创建回调
    connector->read(100,readCallback); // 读取100个字节 成功后 产生回调
}
</pre>

**Comment by peakflys** [comment]
这种方式挺好

2014-04-08 19:43 GMT+08:00 jijinlong notifications@github.com:

> 主要是网络接口 待定版
> 
> class ReadFunction {
> public:
>     void operator()(void *content,unsigned int len)
>     {
> 
> ```
> }
> ```
> 
> };
> int main()
> {
>     IConnector *connector = makeConnector(makeAddr("ip",port));
>     IReactor *reactor = makeReactor();
>     reactor->add(connector);
>     ReadFunction readCallback;
>     connector->read(100,readCallback); // 读取100个字节 成功后 产生回调
> }
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Lang4/server/issues/3
> .

## 

# 

Best Wishes
Jeffrey Tian
